<?php
include_once "helper-functions.php";
add_action('wp_ajax_nopriv_submit_invitation_request', 'submit_invitation_request');
add_action('wp_ajax_submit_invitation_request', 'submit_invitation_request');

function submit_invitation_request() {
    $result = array(
        'success' => false
    );
    $headers[] = 'From: ElsieGram Invitation <invites@elsiegram.com>';
    $emailSent = wp_mail("garrett.estrin@gmail.com", "ElsieGram Invitation Request", "Name: " . $_GET['name'] . " Email: " . $_GET['email'] . ".", $headers);
    if($emailSent) {
        $result['success'] = true;
    }
    return wp_send_json($result);
}

add_action('wp_ajax_submit_elsiegram_post', 'submit_elsiegram_post');

function submit_elsiegram_post() {
    $result = array (
        'success' => false
    );
    if(isset($_POST["caption"]) && isset($_FILES["image"])) {
        if ( ! function_exists( 'wp_handle_upload' ) ) {
            require_once( ABSPATH . 'wp-admin/includes/file.php' );
        }
        $uploadedfile = $_FILES['image'];
        $imageNameArray = explode(".", $uploadedfile['name']);
        $uploadedfile['name'] = $imageNameArray[0] . time() . "." . $imageNameArray[1];
        $upload_overrides = array(
            'test_form' => false
        );
         
        $movefile = wp_handle_upload( $uploadedfile, $upload_overrides );
         
        if ( $movefile && ! isset( $movefile['error'] ) ) {
            compressImage($movefile);
            // create post from image

            // Create post object
            $imagePostData = array(
                'post_status' => 'publish',
                'post_excerpt' => $_POST["caption"],
                'guid' => $movefile["url"],
                'post_type' => 'attachment',
                'post_mime_type' => $movefile["type"]
            );
            
            // Insert the post into the database
            $imagePostResponse = wp_insert_post( $imagePostData );
            $postData = array(
                'post_status' => 'publish',
                'post_type' => 'post',
                'content' => '<!-- wp:paragraph --> <p> </p> <!-- /wp:paragraph -->',
                'post_excerpt' => ' ',
                'post_title' => $_POST["caption"]
            );
            if($imagePostResponse) {
                // need yyyy/mm/imagename
                add_post_meta($imagePostResponse, "_wp_attached_file", date("Y") . "/" . date("m") . "/" . $uploadedfile["name"]);
                // add_post_meta($imagePostResponse, "_wp_attachment_metadata", )
                $postResponse = wp_insert_post( $postData );
                if($postResponse) {
                    $metaPostResponse = add_post_meta($postResponse, "_thumbnail_id", $imagePostResponse);
                    if($metaPostResponse) {
                        $result["success"] = true;
                        addPostToMicroservice(wp_encode_emoji($_POST["caption"]), $movefile["url"]);
                    }
                }
            }
        } else {
            /*
             * Error generated by _wp_handle_upload()
             * @see _wp_handle_upload() in wp-admin/includes/file.php
             */
            $result["message"] = "There was an error uploading the image";
        }
    }
    
    return wp_send_json($result);
}

add_action('wp_ajax_nopriv_ui_login', 'ui_login');
add_action('wp_ajax_ui_login', 'ui_login');
function ui_login() {
    $result = array (
        'success' => false
    );
    $result["success"] = wp_login($_POST['email'], $_POST['password']);
    if($result["success"]) {
        $userId = email_exists($_POST["email"]);
        wp_set_auth_cookie($userId, true);
        setAuthCookie();
    }
    return wp_send_json($result);
}